"""
app/__init__.py

Minimal working version for UniTrack
"""

import sys
import os

# 🔥 FIX: ensure project root is always available
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if BASE_DIR not in sys.path:
    sys.path.insert(0, BASE_DIR)

from flask import Flask, redirect, url_for, session
from flask_login import LoginManager, current_user
from flask_migrate import Migrate

from config import Config
from .database import db

# ✅ REGISTERED BLUEPRINTS
from .routes.auth_routes import auth_bp
from .routes.admin_views import admin_views_bp
from .routes.student_views import student_views_bp
from .routes.personal_views import personal_views_bp
from .routes.professor_views import professor_views_bp

# ✅ ADMIN SEED
from .services.admin_seed_service import seed_default_admin

# Flask-Login manager
login_manager = LoginManager()
migrate = Migrate()


@login_manager.user_loader
def load_user(user_id):
    from .services.user_service import get_user_by_id
    return get_user_by_id(int(user_id))


def create_app():

    app = Flask(__name__)

    app.config.from_object(Config)

    app.config["SQLALCHEMY_DATABASE_URI"] = Config.SQLALCHEMY_DATABASE_URI
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = Config.SQLALCHEMY_TRACK_MODIFICATIONS
    app.config["SECRET_KEY"] = os.environ.get("SECRET_KEY", Config.SECRET_KEY)

    db.init_app(app)
    migrate.init_app(app, db)

    login_manager.init_app(app)
    login_manager.login_view = None

    # ✅ GLOBAL LANGUAGE HELPERS
    TRANSLATIONS = {
        "en": {
            "dashboard": "Dashboard",
            "access_control": "Access Control",
            "access_scanner": "Access Scanner",
            "attendance_history": "Attendance History",
            "settings": "Settings",
            "configuration": "Configuration",
            "Configuration": "Configuration",
            "validation_codes": "Validation Codes",
            "users": "Users",
            "logout": "Logout",
            "student": "Student",
            "professor": "Professor",
            "staff": "Staff",
            "admin": "Admin",
            "active": "Active",
            "offline": "Offline",
            "welcome": "Welcome",
            "login": "Login",
            "register": "Register",
            "forgot_password": "Forgot Password",
            "reset_password": "Reset Password",
            "save": "Save",
            "cancel": "Cancel",
            "english": "English",
            "spanish": "Spanish",
            "student_dashboard_subtitle": "This is your main UniTrack dashboard. From here you can access your attendance history, open the access control scanner, and review your student account information.",
            "professor_dashboard_subtitle": "Welcome to your UniTrack professor dashboard. From here you can access your access control scanner and review your professor account information.",
            "admin_dashboard_subtitle": "Welcome to your UniTrack admin dashboard. From here you can manage users, validation codes, access control, and your administrator account information.",
            "user_id": "User ID",
            "inactive": "Inactive",
            "open_access_scanner": "Open Access Scanner",
            "view_attendance_history": "View Attendance History",
            "view_configuration": "View Configuration",
            "role": "Role",
            "your_role": "Your UniTrack role",
            "account_status": "Account Status",
            "session_state": "Session state",
            "unique_identifier": "Your unique identifier",
            "student_information": "Student Information",
            "student_info_subtitle": "Review your personal account details currently stored in UniTrack.",
            "professor_information": "Professor Information",
            "professor_info_subtitle": "Review your personal account details currently stored in UniTrack.",
            "admin_information": "Administrator Information",
            "admin_info_subtitle": "Review your administrator account details currently stored in UniTrack.",
            "full_name": "Full Name",
            "username": "Username",
            "email": "Email",
            "phone": "Phone",
            "status": "Status",
            "workspace": "Workspace",
            "student_panel_footer": "UniTrack Student Panel · Mobile Ready Layout",
            "admin_panel_footer": "UniTrack Admin Panel · Mobile Ready Layout",
            "show_password": "Show password",
            "university_name": "Polytechnic University of Baja California",

            "Access Control System": "Access Control System",
            "Use your QR code to check in or check out.": "Use your QR code to check in or check out.",
            "Staff Photo": "Staff Photo",
            "Staff ID / Username:": "Staff ID / Username:",
            "Inside Campus": "Inside Campus",
            "Outside Campus": "Outside Campus",
            "Latest Date": "Latest Date",
            "Check-In Time": "Check-In Time",
            "Check-Out Time": "Check-Out Time",
            "Hours": "Hours",
            "Date": "Date",
            "Search": "Search",
            "Your Access QR Code": "Your Access QR Code",
            "Staff Access QR Code": "Staff Access QR Code",
            "QR Payload": "QR Payload",
            "Copy": "Copy",
            "Copied!": "Copied!",
            "Failed": "Failed",
            "Backup QR ID Code": "Backup QR ID Code",
            "Check In": "Check In",
            "Check Out": "Check Out",
            "Current Status": "Current Status",
            "Staff:": "Staff:",
            "Username:": "Username:",
            "Status:": "Status:",
            "Last Check-In:": "Last Check-In:",
            "Last Check-Out:": "Last Check-Out:",
            "Hours Today:": "Hours Today:",
            "Access History": "Access History",
            "Review your recorded check-ins and check-outs.": "Review your recorded check-ins and check-outs.",
            "record": "record",
            "ID / Username": "ID / Username",
            "Check-In": "Check-In",
            "Check-Out": "Check-Out",
            "Campus access": "Campus access",
            "No access history available yet.": "No access history available yet.",

            "QR Scanner": "QR Scanner",
            "Access QR Scanner": "Access QR Scanner",
            "Simulate the access reader by pasting the staff QR code content.": "Simulate the access reader by pasting the staff QR code content.",
            "QR Content": "QR Content",
            "Scan QR": "Scan QR",
            "Clear": "Clear",
            "Successful Scan": "Successful Scan",
            "Message:": "Message:",
            "Action:": "Action:",
            "Name:": "Name:",
            "Check In:": "Check In:",
            "Check Out:": "Check Out:",
            "Failed Scan": "Failed Scan",
            "HTTP Status Code:": "HTTP Status Code:",
            "Quick Example": "Quick Example",
            "Paste a real QR value like one of these:": "Paste a real QR value like one of these:",

            "Staff Configuration": "Staff Configuration",
            "Staff Panel": "Staff Panel",
            "Manage your personal information and account settings.": "Manage your personal information and account settings.",
            "Update your personal information, security, preferences, and profile image.": "Update your personal information, security, preferences, and profile image.",
            "Profile Photo": "Profile Photo",
            "Upload Photo": "Upload Photo",
            "Contact Information": "Contact Information",
            "First Name": "First Name",
            "Last Name": "Last Name",
            "Security": "Security",
            "Current Password": "Current Password",
            "New Password": "New Password",
            "Confirm Password": "Confirm Password",
            "Save Changes": "Save Changes",

            "Professor Photo": "Professor Photo",
            "Professor ID / Username:": "Professor ID / Username:",
            "Professor Access QR Code": "Professor Access QR Code",
            "Professor:": "Professor:",
            "Simulate the access reader by pasting the professor QR code content.": "Simulate the access reader by pasting the professor QR code content.",
            "Professor Configuration": "Professor Configuration",
            "Professor Panel": "Professor Panel",
            "Manage your professor information and account settings.": "Manage your professor information and account settings.",
            "Update your professor information, security, preferences, and profile image.": "Update your professor information, security, preferences, and profile image.",

            "Admin Panel": "Admin Panel",
            "Admin Configuration": "Admin Configuration",
            "Manage your administrator information and account settings.": "Manage your administrator information and account settings.",
            "Update your administrator information, security, preferences, and profile image.": "Update your administrator information, security, preferences, and profile image.",
            "Administrator": "Administrator",
            "Admin Access QR Code": "Admin Access QR Code",
            "Admin Photo": "Admin Photo",
            "Admin ID / Username:": "Admin ID / Username:",
            "Admin:": "Admin:",
            "Simulate the access reader by pasting the admin QR code content.": "Simulate the access reader by pasting the admin QR code content.",
            "Manage Users": "Manage Users",
            "Manage registered users in UniTrack.": "Manage registered users in UniTrack.",
            "Search users by name, email, username, role, or user ID.": "Search users by name, email, username, role, or user ID.",
            "Validation Code Management": "Validation Code Management",
            "Create and review validation codes for user registration.": "Create and review validation codes for user registration.",
            "Create Validation Code": "Create Validation Code",
            "Code": "Code",
            "Generated By": "Generated By",
            "Expires At": "Expires At",
            "Created At": "Created At",
            "Used": "Used",
            "Unused": "Unused",
            "Used At": "Used At",
            "Used By": "Used By",
            "Actions": "Actions",
            "Edit": "Edit",
            "Delete": "Delete",
            "Change Role": "Change Role",
            "Change Password": "Change Password",
            "Update User ID": "Update User ID",
            "User Management": "User Management",
            "Search by name, username, email, phone, or user ID": "Search by name, username, email, phone, or user ID",
            "All Roles": "All Roles",
            "No users found.": "No users found.",
            "No validation codes found.": "No validation codes found.",
            "Password": "Password",
            "Confirm New Password": "Confirm New Password",
            "Select Role": "Select Role",
            "Delete User": "Delete User",
            "Edit User": "Edit User",
            "Update user information.": "Update user information.",
            "Update User ID Code": "Update User ID Code",
            "Generate Code": "Generate Code",
            "Expiration": "Expiration",
            "Role:": "Role:",
            "Email:": "Email:",
            "Phone:": "Phone:",
            "User ID:": "User ID:",

            "Admin Dashboard": "Admin Dashboard",
            "Admin Overview": "Admin Overview",
            "Monitor validation codes, access activity, and live system totals from one control center.": "Monitor validation codes, access activity, and live system totals from one control center.",
            "Welcome to the UniTrack Admin Control Center": "Welcome to the UniTrack Admin Control Center",
            "This dashboard is the first admin version aligned with the student design system. From here, administrators will manage validation codes, review live access totals, monitor active users, and control access operations for students, teachers, staff, and admins.": "This dashboard is the first admin version aligned with the student design system. From here, administrators will manage validation codes, review live access totals, monitor active users, and control access operations for students, teachers, staff, and admins.",
            "Created Codes": "Created Codes",
            "All generated codes in the system": "All generated codes in the system",
            "Used Codes": "Used Codes",
            "Codes already consumed by users": "Codes already consumed by users",
            "Active Users Today": "Active Users Today",
            "Users currently active in today’s flow": "Users currently active in today’s flow",
            "Students Signed In": "Students Signed In",
            "Registered student accounts currently tracked": "Registered student accounts currently tracked",
            "Today Check-Ins": "Today Check-Ins",
            "All check-in records detected today": "All check-in records detected today",
            "Today Check-Outs": "Today Check-Outs",
            "All check-out records detected today": "All check-out records detected today",
            "Today Activity by Role": "Today Activity by Role",
            "Quick role breakdown for daily access and live activity totals.": "Quick role breakdown for daily access and live activity totals.",
            "Students": "Students",
            "Teachers": "Teachers",
            "Checked In:": "Checked In:",
            "Checked Out:": "Checked Out:",
            "Active Today:": "Active Today:",
            "Validation Code Overview": "Validation Code Overview",
            "Initial admin dashboard block for code activity and role-based creation tracking.": "Initial admin dashboard block for code activity and role-based creation tracking.",
            "Expires": "Expires",
            "Expired": "Expired",
            "No limit": "No limit",
            "No validation codes available yet.": "No validation codes available yet.",
            "Quick Actions": "Quick Actions",
            "Fast navigation for the first admin build. These sections can be expanded later without changing the design system.": "Fast navigation for the first admin build. These sections can be expanded later without changing the design system.",
            "Create New Validation Code": "Create New Validation Code",
            "Open the validation-code section to create role-based codes with time expiration.": "Open the validation-code section to create role-based codes with time expiration.",
            "Open Validation Codes": "Open Validation Codes",
            "Review Active Users": "Review Active Users",
            "Open user monitoring to review who is active and how many role accounts exist.": "Open user monitoring to review who is active and how many role accounts exist.",
            "Open Users": "Open Users",
            "Access Control Monitor": "Access Control Monitor",
            "Check live check-in and check-out flow for all tracked roles and today’s activity.": "Check live check-in and check-out flow for all tracked roles and today’s activity.",
            "Open Access Control": "Open Access Control",
            "Access Search": "Access Search",
            "Search by name, ID, role, and date to review access records.": "Search by name, ID, role, and date to review access records.",
            "Search by full name or ID": "Search by full name or ID",
            "Teacher": "Teacher",
            "ID": "ID",
            "Name": "Name",
            "Active": "Active",
            "Closed": "Closed",
            "Pending": "Pending",
            "No access history data available yet.": "No access history data available yet.",
            "Live Presence Feed": "Live Presence Feed",
            "People currently active or recently updated in the system.": "People currently active or recently updated in the system.",
            "ID:": "ID:",
            "Last Action:": "Last Action:",
            "Time:": "Time:",
            "No live activity yet": "No live activity yet",
            "Waiting": "Waiting",
            "Live presence data will appear here once access activity is available.": "Live presence data will appear here once access activity is available.",
            "System Notes": "System Notes",
            "Planned admin-only control features based on your system design.": "Planned admin-only control features based on your system design.",
            "Role-Based Code Expiration": "Role-Based Code Expiration",
            "Ready": "Ready",
            "Validation codes are designed to support role selection and time limits like 24 or 48 hours.": "Validation codes are designed to support role selection and time limits like 24 or 48 hours.",
            "Admin Access Participation": "Admin Access Participation",
            "Included": "Included",
            "Admins will also use the same access-control flow, QR logic, and history structure as other roles.": "Admins will also use the same access-control flow, QR logic, and history structure as other roles.",
            "Recent Admin Activity": "Recent Admin Activity",
            "Latest admin operations and important updates.": "Latest admin operations and important updates.",
            "No admin activity yet": "No admin activity yet",
            "Empty": "Empty",
            "New admin actions will appear here once dashboard logic is connected.": "New admin actions will appear here once dashboard logic is connected.",
            "View Users": "View Users",
        },
        "es": {
            "dashboard": "Panel",
            "access_control": "Control de Acceso",
            "access_scanner": "Escáner de Acceso",
            "attendance_history": "Historial de Asistencia",
            "settings": "Configuración",
            "configuration": "Configuración",
            "Configuration": "Configuración",
            "validation_codes": "Códigos de Validación",
            "users": "Usuarios",
            "logout": "Cerrar Sesión",
            "student": "Estudiante",
            "professor": "Profesor",
            "staff": "Personal",
            "admin": "Administrador",
            "active": "Activo",
            "offline": "Desconectado",
            "welcome": "Bienvenido",
            "login": "Iniciar Sesión",
            "register": "Registrarse",
            "forgot_password": "Olvidé mi Contraseña",
            "reset_password": "Restablecer Contraseña",
            "save": "Guardar",
            "cancel": "Cancelar",
            "english": "Inglés",
            "spanish": "Español",
            "student_dashboard_subtitle": "Este es tu panel principal de UniTrack. Desde aquí puedes acceder a tu historial de asistencia, abrir el escáner de control de acceso y revisar la información de tu cuenta estudiantil.",
            "professor_dashboard_subtitle": "Bienvenido a tu panel de profesor de UniTrack. Desde aquí puedes acceder a tu escáner de control de acceso y revisar la información de tu cuenta de profesor.",
            "admin_dashboard_subtitle": "Bienvenido a tu panel de administrador de UniTrack. Desde aquí puedes gestionar usuarios, códigos de validación, control de acceso y la información de tu cuenta de administrador.",
            "user_id": "ID de Usuario",
            "inactive": "Inactivo",
            "open_access_scanner": "Abrir Escáner de Acceso",
            "view_attendance_history": "Ver Historial de Asistencia",
            "view_configuration": "Ver Configuración",
            "role": "Rol",
            "your_role": "Tu rol en UniTrack",
            "account_status": "Estado de la Cuenta",
            "session_state": "Estado de la sesión",
            "unique_identifier": "Tu identificador único",
            "student_information": "Información del Estudiante",
            "student_info_subtitle": "Revisa los datos personales de tu cuenta almacenados actualmente en UniTrack.",
            "professor_information": "Información del Profesor",
            "professor_info_subtitle": "Revisa los datos personales de tu cuenta almacenados actualmente en UniTrack.",
            "admin_information": "Información del Administrador",
            "admin_info_subtitle": "Revisa los datos de tu cuenta de administrador almacenados actualmente en UniTrack.",
            "full_name": "Nombre Completo",
            "username": "Nombre de Usuario",
            "email": "Correo Electrónico",
            "phone": "Teléfono",
            "status": "Estado",
            "workspace": "Espacio de Trabajo",
            "student_panel_footer": "Panel de Estudiante UniTrack · Diseño Listo para Móvil",
            "admin_panel_footer": "Panel de Administrador UniTrack · Diseño Listo para Móvil",
            "show_password": "Mostrar contraseña",
            "university_name": "Universidad Politécnica de Baja California",

            "Access Control System": "Sistema de Control de Acceso",
            "Use your QR code to check in or check out.": "Usa tu código QR para registrar entrada o salida.",
            "Staff Photo": "Foto del Personal",
            "Staff ID / Username:": "ID del Personal / Usuario:",
            "Inside Campus": "Dentro del Campus",
            "Outside Campus": "Fuera del Campus",
            "Latest Date": "Última Fecha",
            "Check-In Time": "Hora de Entrada",
            "Check-Out Time": "Hora de Salida",
            "Hours": "Horas",
            "Date": "Fecha",
            "Search": "Buscar",
            "Your Access QR Code": "Tu Código QR de Acceso",
            "Staff Access QR Code": "Código QR de Acceso del Personal",
            "QR Payload": "Contenido del QR",
            "Copy": "Copiar",
            "Copied!": "¡Copiado!",
            "Failed": "Error",
            "Backup QR ID Code": "Código QR de Respaldo",
            "Check In": "Registrar Entrada",
            "Check Out": "Registrar Salida",
            "Current Status": "Estado Actual",
            "Staff:": "Personal:",
            "Username:": "Usuario:",
            "Status:": "Estado:",
            "Last Check-In:": "Última Entrada:",
            "Last Check-Out:": "Última Salida:",
            "Hours Today:": "Horas Hoy:",
            "Access History": "Historial de Acceso",
            "Review your recorded check-ins and check-outs.": "Revisa tus entradas y salidas registradas.",
            "record": "registro",
            "ID / Username": "ID / Usuario",
            "Check-In": "Entrada",
            "Check-Out": "Salida",
            "Campus access": "Acceso al campus",
            "No access history available yet.": "Aún no hay historial de acceso disponible.",

            "QR Scanner": "Escáner QR",
            "Access QR Scanner": "Escáner QR de Acceso",
            "Simulate the access reader by pasting the staff QR code content.": "Simula el lector de acceso pegando el contenido del código QR del personal.",
            "QR Content": "Contenido QR",
            "Scan QR": "Escanear QR",
            "Clear": "Limpiar",
            "Successful Scan": "Escaneo Exitoso",
            "Message:": "Mensaje:",
            "Action:": "Acción:",
            "Name:": "Nombre:",
            "Check In:": "Entrada:",
            "Check Out:": "Salida:",
            "Failed Scan": "Escaneo Fallido",
            "HTTP Status Code:": "Código de Estado HTTP:",
            "Quick Example": "Ejemplo Rápido",
            "Paste a real QR value like one of these:": "Pega un valor QR real como uno de estos:",

            "Staff Configuration": "Configuración del Personal",
            "Staff Panel": "Panel de Personal",
            "Manage your personal information and account settings.": "Administra tu información personal y la configuración de tu cuenta.",
            "Update your personal information, security, preferences, and profile image.": "Actualiza tu información personal, seguridad, preferencias e imagen de perfil.",
            "Profile Photo": "Foto de Perfil",
            "Upload Photo": "Subir Foto",
            "Contact Information": "Información de Contacto",
            "First Name": "Nombre",
            "Last Name": "Apellido",
            "Security": "Seguridad",
            "Current Password": "Contraseña Actual",
            "New Password": "Nueva Contraseña",
            "Confirm Password": "Confirmar Contraseña",
            "Save Changes": "Guardar Cambios",

            "Professor Photo": "Foto del Profesor",
            "Professor ID / Username:": "ID del Profesor / Usuario:",
            "Professor Access QR Code": "Código QR de Acceso del Profesor",
            "Professor:": "Profesor:",
            "Simulate the access reader by pasting the professor QR code content.": "Simula el lector de acceso pegando el contenido del código QR del profesor.",
            "Professor Configuration": "Configuración del Profesor",
            "Professor Panel": "Panel del Profesor",
            "Manage your professor information and account settings.": "Administra tu información de profesor y la configuración de tu cuenta.",
            "Update your professor information, security, preferences, and profile image.": "Actualiza tu información de profesor, seguridad, preferencias e imagen de perfil.",

            "Admin Panel": "Panel de Administrador",
            "Admin Configuration": "Configuración del Administrador",
            "Manage your administrator information and account settings.": "Administra la información de tu administrador y la configuración de tu cuenta.",
            "Update your administrator information, security, preferences, and profile image.": "Actualiza la información de tu administrador, seguridad, preferencias e imagen de perfil.",
            "Administrator": "Administrador",
            "Admin Access QR Code": "Código QR de Acceso del Administrador",
            "Admin Photo": "Foto del Administrador",
            "Admin ID / Username:": "ID del Administrador / Usuario:",
            "Admin:": "Administrador:",
            "Simulate the access reader by pasting the admin QR code content.": "Simula el lector de acceso pegando el contenido del código QR del administrador.",
            "Manage Users": "Gestionar Usuarios",
            "Manage registered users in UniTrack.": "Gestiona los usuarios registrados en UniTrack.",
            "Search users by name, email, username, role, or user ID.": "Busca usuarios por nombre, correo, usuario, rol o ID de usuario.",
            "Validation Code Management": "Gestión de Códigos de Validación",
            "Create and review validation codes for user registration.": "Crea y revisa códigos de validación para el registro de usuarios.",
            "Create Validation Code": "Crear Código de Validación",
            "Code": "Código",
            "Generated By": "Generado Por",
            "Expires At": "Expira El",
            "Created At": "Creado El",
            "Used": "Usado",
            "Unused": "Sin Usar",
            "Used At": "Usado El",
            "Used By": "Usado Por",
            "Actions": "Acciones",
            "Edit": "Editar",
            "Delete": "Eliminar",
            "Change Role": "Cambiar Rol",
            "Change Password": "Cambiar Contraseña",
            "Update User ID": "Actualizar ID de Usuario",
            "User Management": "Gestión de Usuarios",
            "Search by name, username, email, phone, or user ID": "Buscar por nombre, usuario, correo, teléfono o ID de usuario",
            "All Roles": "Todos los Roles",
            "No users found.": "No se encontraron usuarios.",
            "No validation codes found.": "No se encontraron códigos de validación.",
            "Password": "Contraseña",
            "Confirm New Password": "Confirmar Nueva Contraseña",
            "Select Role": "Seleccionar Rol",
            "Delete User": "Eliminar Usuario",
            "Edit User": "Editar Usuario",
            "Update user information.": "Actualiza la información del usuario.",
            "Update User ID Code": "Actualizar Código ID de Usuario",
            "Generate Code": "Generar Código",
            "Expiration": "Expiración",
            "Role:": "Rol:",
            "Email:": "Correo:",
            "Phone:": "Teléfono:",
            "User ID:": "ID de Usuario:",

            "Admin Dashboard": "Panel de Administrador",
            "Admin Overview": "Resumen del Administrador",
            "Monitor validation codes, access activity, and live system totals from one control center.": "Monitorea códigos de validación, actividad de acceso y totales en vivo del sistema desde un solo centro de control.",
            "Welcome to the UniTrack Admin Control Center": "Bienvenido al Centro de Control de Administrador de UniTrack",
            "This dashboard is the first admin version aligned with the student design system. From here, administrators will manage validation codes, review live access totals, monitor active users, and control access operations for students, teachers, staff, and admins.": "Este panel es la primera versión de administrador alineada con el sistema de diseño estudiantil. Desde aquí, los administradores gestionarán códigos de validación, revisarán totales de acceso en vivo, monitorearán usuarios activos y controlarán operaciones de acceso para estudiantes, profesores, personal y administradores.",
            "Created Codes": "Códigos Creados",
            "All generated codes in the system": "Todos los códigos generados en el sistema",
            "Used Codes": "Códigos Usados",
            "Codes already consumed by users": "Códigos ya utilizados por los usuarios",
            "Active Users Today": "Usuarios Activos Hoy",
            "Users currently active in today’s flow": "Usuarios actualmente activos en el flujo de hoy",
            "Students Signed In": "Estudiantes Registrados",
            "Registered student accounts currently tracked": "Cuentas de estudiantes registradas actualmente",
            "Today Check-Ins": "Entradas de Hoy",
            "All check-in records detected today": "Todos los registros de entrada detectados hoy",
            "Today Check-Outs": "Salidas de Hoy",
            "All check-out records detected today": "Todos los registros de salida detectados hoy",
            "Today Activity by Role": "Actividad de Hoy por Rol",
            "Quick role breakdown for daily access and live activity totals.": "Resumen rápido por rol para accesos diarios y totales de actividad en vivo.",
            "Students": "Estudiantes",
            "Teachers": "Profesores",
            "Checked In:": "Entradas:",
            "Checked Out:": "Salidas:",
            "Active Today:": "Activos Hoy:",
            "Validation Code Overview": "Resumen de Códigos de Validación",
            "Initial admin dashboard block for code activity and role-based creation tracking.": "Bloque inicial del panel de administrador para actividad de códigos y seguimiento de creación por rol.",
            "Expires": "Expira",
            "Expired": "Expirado",
            "No limit": "Sin límite",
            "No validation codes available yet.": "No hay códigos de validación disponibles todavía.",
            "Quick Actions": "Acciones Rápidas",
            "Fast navigation for the first admin build. These sections can be expanded later without changing the design system.": "Navegación rápida para la primera versión del administrador. Estas secciones pueden ampliarse después sin cambiar el sistema de diseño.",
            "Create New Validation Code": "Crear Nuevo Código de Validación",
            "Open the validation-code section to create role-based codes with time expiration.": "Abre la sección de códigos de validación para crear códigos por rol con tiempo de expiración.",
            "Open Validation Codes": "Abrir Códigos de Validación",
            "Review Active Users": "Revisar Usuarios Activos",
            "Open user monitoring to review who is active and how many role accounts exist.": "Abre el monitoreo de usuarios para revisar quién está activo y cuántas cuentas existen por rol.",
            "Open Users": "Abrir Usuarios",
            "Access Control Monitor": "Monitor de Control de Acceso",
            "Check live check-in and check-out flow for all tracked roles and today’s activity.": "Revisa el flujo en vivo de entradas y salidas para todos los roles registrados y la actividad de hoy.",
            "Open Access Control": "Abrir Control de Acceso",
            "Access Search": "Búsqueda de Accesos",
            "Search by name, ID, role, and date to review access records.": "Busca por nombre, ID, rol y fecha para revisar registros de acceso.",
            "Search by full name or ID": "Buscar por nombre completo o ID",
            "Teacher": "Profesor",
            "ID": "ID",
            "Name": "Nombre",
            "Active": "Activo",
            "Closed": "Cerrado",
            "Pending": "Pendiente",
            "No access history data available yet.": "Aún no hay datos de historial de acceso disponibles.",
            "Live Presence Feed": "Actividad en Vivo",
            "People currently active or recently updated in the system.": "Personas actualmente activas o recientemente actualizadas en el sistema.",
            "ID:": "ID:",
            "Last Action:": "Última Acción:",
            "Time:": "Hora:",
            "No live activity yet": "Aún no hay actividad en vivo",
            "Waiting": "En Espera",
            "Live presence data will appear here once access activity is available.": "Los datos de actividad en vivo aparecerán aquí una vez que haya actividad de acceso disponible.",
            "System Notes": "Notas del Sistema",
            "Planned admin-only control features based on your system design.": "Funciones de control solo para administradores planificadas según el diseño de tu sistema.",
            "Role-Based Code Expiration": "Expiración de Código por Rol",
            "Ready": "Listo",
            "Validation codes are designed to support role selection and time limits like 24 or 48 hours.": "Los códigos de validación están diseñados para admitir selección de rol y límites de tiempo como 24 o 48 horas.",
            "Admin Access Participation": "Participación de Acceso del Administrador",
            "Included": "Incluido",
            "Admins will also use the same access-control flow, QR logic, and history structure as other roles.": "Los administradores también usarán el mismo flujo de control de acceso, lógica QR y estructura de historial que los otros roles.",
            "Recent Admin Activity": "Actividad Reciente del Administrador",
            "Latest admin operations and important updates.": "Últimas operaciones del administrador y actualizaciones importantes.",
            "No admin activity yet": "Aún no hay actividad del administrador",
            "Empty": "Vacío",
            "New admin actions will appear here once dashboard logic is connected.": "Las nuevas acciones del administrador aparecerán aquí una vez que la lógica del panel esté conectada.",
            "View Users": "Ver Usuarios",
        },
    }

    def get_current_language():
        if current_user.is_authenticated:
            user_language = getattr(current_user, "language", None)
            if user_language in {"en", "es"}:
                session["language"] = user_language
                return user_language

        session_language = session.get("language")
        if session_language in {"en", "es"}:
            return session_language

        session["language"] = "en"
        return "en"

    def t(key):
        language = get_current_language()
        return TRANSLATIONS.get(language, TRANSLATIONS["en"]).get(key, key)

    @app.context_processor
    def inject_global_translations():
        return {
            "t": t,
            "current_language": get_current_language(),
        }

    # ✅ REGISTER BLUEPRINTS
    app.register_blueprint(auth_bp)
    app.register_blueprint(admin_views_bp)
    app.register_blueprint(student_views_bp)
    app.register_blueprint(personal_views_bp)
    app.register_blueprint(professor_views_bp)

    with app.app_context():
        # minimal models load
        from .models.user_model import User
        from .models.validation_code_model import ValidationCode

        db.create_all()

        # 🔥 CREATE DEFAULT ADMIN
        seed_default_admin()

    # ✅ ROOT → LOGIN PAGE
    @app.route("/")
    def home():
        return redirect(url_for("auth.login_page"))

    return app